-- huge table of constants for game design tuning
C = {
	DRAW_HITBOX_DEBUG = false,

	-- destination_distance = 9000, -- in ticks, 9000 ticks = 5 mins
	DESTINATION_DISTANCE = 5400,

	SHADOW_OFFSET = 2,
	BOUNDS_OFFSET_SIDES = 8,
	BOUNDS_OFFSET_TOP = 32, -- a lot more things happen on top of the screen
	BOUNDS_OFFSET_BOTTOM = 8,
	BOUNDS_SAFE = 16,
	SPAWN_BOUND_LF = 16,
	SPAWN_BOUND_RT = 127 - 16 *2,

	LAYER1_SCROLL_SPEED = 2,
	LAYER2_SCROLL_SPEED = 3,
	LAYER3_SCROLL_SPEED = 6,

	PLAYER_FIRERATE = 5, -- Firerates are all in ticks
	PLAYER_SPEED_FAST = 4,
	PLAYER_SPEED_SLOW = 1,

	PLAYER_HP_START = 4,

	PLAYER_AMMO_START = 4,
	PLAYER_AMMO_MAX = 8,

	HARVEST_DISTANCE_SMALL = 12,
	HARVEST_DISTANCE_MEDIUM = 15,
	HARVEST_DISTANCE_LARGE = 20,
	HARVEST_COMPLETE = 60, -- 2 seconds

	FBULLET_SPEED = -12,

	SPAWNRATE_ENEMY_MIN = 75,
	SPAWNRATE_ENEMY_RANGE = 30,
	SPAWNRATE_ASTEROID_MIN = 45,
	SPAWNRATE_ASTEROID_MAX = 45,

	RILEY_MOVE_VY = 1,
	RILEY_FIRERATE = 45,
	RILEY_BULLET_VEL = 1.5,

	DULCE_MOVE_VY = 6,
	DULCE_FIRERATE = 7,
	DULCE_BULLET_VY = 2,

	AUGUSTUS_MOVE_VY = 1,
	AUGUSTUS_FIRERATE = 30,
	AUGUSTUS_BULLET_MEDIAL_VY = 2,
	AUGUSTUS_BULLET_LATERAL_Vx = 1,
	AUGUSTUS_BULLET_LATERAL_Vy = 1.5,

	HAMMERHEAD_MOVE_VY = 1,
	HAMMERHEAD_FIRERATE = 30,
	HAMMERHEAD_BULLET_VX = 2,
	HAMMERHEAD_BULLET_VY = 1,

	KOLTAR_FIRERATE = 30,
	KOLTAR_BULLET_VEL = 2,

	ASTEROID_LARGE_VEL_MAX = 1.5,

	EXPLOSION_SMALL_AMT = 4,
	EXPLOSION_SMALL_AMT_RANGE = 3,
	EXPLOSION_MEDIUM_AMT = 6,
	EXPLOSION_MEDIUM_AMT_RANGe = 4,
	EXPLOSION_LARGE_AMT = 8,
	EXPLOSION_LARGE_AMT_RANGE = 5,
	
	STAR_RADIUS_MIN = 1,
	STAR_RADIUS_RANGE = 3,
	
	SMOKE_RADIUS_INIT = 10,
	SMOKE_RADIUS_RANGE = 5,
	SMOKE_DECREMENT_RATE = 0.5,
	
	CARCASS_MOVE_VY = 2,
	
	SPARK_INCREMENT_RATE = 2,	
	SPARK_COLOR_1 = 8,
	SPARK_COLOR_2 = 10,

	FRAGMENT_MOVE_VEL_MIN  = 1,
	FRAGMENT_MOVE_VEL_RANGE = 1.5,
	FRAGMENT_AMT_MIN = 5,
	FRAGMENT_AMT_RANGE = 5,

	KEY_A = 5,
	KEY_B = 4
}